//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayMe.Apps.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PayMe.Apps.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corderoski.
        /// </summary>
        internal static string AppAuthor {
            get {
                return ResourceManager.GetString("AppAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Me, Dude!.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Label_About {
            get {
                return ResourceManager.GetString("Label_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Label_Accept {
            get {
                return ResourceManager.GetString("Label_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Label_Add {
            get {
                return ResourceManager.GetString("Label_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Label_Cancel {
            get {
                return ResourceManager.GetString("Label_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Label_Contact {
            get {
                return ResourceManager.GetString("Label_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string Label_Contacts {
            get {
                return ResourceManager.GetString("Label_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Label_Dashboard {
            get {
                return ResourceManager.GetString("Label_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Label_Description {
            get {
                return ResourceManager.GetString("Label_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by.
        /// </summary>
        internal static string Label_DevelopedBy {
            get {
                return ResourceManager.GetString("Label_DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --.
        /// </summary>
        internal static string Label_EmptySelection {
            get {
                return ResourceManager.GetString("Label_EmptySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Label_Error {
            get {
                return ResourceManager.GetString("Label_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Error.
        /// </summary>
        internal static string Label_Error_SyncError_Title {
            get {
                return ResourceManager.GetString("Label_Error_SyncError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it!.
        /// </summary>
        internal static string Label_GotIt {
            get {
                return ResourceManager.GetString("Label_GotIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Label_Help {
            get {
                return ResourceManager.GetString("Label_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How-To.
        /// </summary>
        internal static string Label_HowTo {
            get {
                return ResourceManager.GetString("Label_HowTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Label_Info {
            get {
                return ResourceManager.GetString("Label_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Authentication Enabled.
        /// </summary>
        internal static string Label_IsAutoAuthenticationEnabled {
            get {
                return ResourceManager.GetString("Label_IsAutoAuthenticationEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Debts.
        /// </summary>
        internal static string Label_Menu_PrimaryTab_MyDebts {
            get {
                return ResourceManager.GetString("Label_Menu_PrimaryTab_MyDebts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Dues.
        /// </summary>
        internal static string Label_Menu_Secondary_OthersDebts {
            get {
                return ResourceManager.GetString("Label_Menu_Secondary_OthersDebts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money.
        /// </summary>
        internal static string Label_Money {
            get {
                return ResourceManager.GetString("Label_Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Label_No {
            get {
                return ResourceManager.GetString("Label_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Label_Notes {
            get {
                return ResourceManager.GetString("Label_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        internal static string Label_Okay {
            get {
                return ResourceManager.GetString("Label_Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        internal static string Label_Person {
            get {
                return ResourceManager.GetString("Label_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Label_Profile {
            get {
                return ResourceManager.GetString("Label_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Sharing Phrase.
        /// </summary>
        internal static string Label_Profile_CustomSharingPhrase {
            get {
                return ResourceManager.GetString("Label_Profile_CustomSharingPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Sync:.
        /// </summary>
        internal static string Label_Profile_LastSync {
            get {
                return ResourceManager.GetString("Label_Profile_LastSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {} for signin and backup your data..
        /// </summary>
        internal static string Label_Profile_SigninMessage {
            get {
                return ResourceManager.GetString("Label_Profile_SigninMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display empty (zero-based) transactions.
        /// </summary>
        internal static string Label_Settings_DisplayEmptyTransaction {
            get {
                return ResourceManager.GetString("Label_Settings_DisplayEmptyTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string Label_Share {
            get {
                return ResourceManager.GetString("Label_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string Label_SignIn {
            get {
                return ResourceManager.GetString("Label_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string Label_SignOut {
            get {
                return ResourceManager.GetString("Label_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string Label_SyncExecution_None {
            get {
                return ResourceManager.GetString("Label_SyncExecution_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string Label_Tags {
            get {
                return ResourceManager.GetString("Label_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toys.
        /// </summary>
        internal static string Label_TagSelector_PlaceholderHelper {
            get {
                return ResourceManager.GetString("Label_TagSelector_PlaceholderHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} transaction.
        /// </summary>
        internal static string Label_Transaction_OneTransactionCountFormatted {
            get {
                return ResourceManager.GetString("Label_Transaction_OneTransactionCountFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uber, Wendy&apos;s.
        /// </summary>
        internal static string Label_Transaction_TagEditorInitialText {
            get {
                return ResourceManager.GetString("Label_Transaction_TagEditorInitialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} transactions.
        /// </summary>
        internal static string Label_Transaction_TransactionsCountFormatted {
            get {
                return ResourceManager.GetString("Label_Transaction_TransactionsCountFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string Label_Warning_Title {
            get {
                return ResourceManager.GetString("Label_Warning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Label_Yes {
            get {
                return ResourceManager.GetString("Label_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lets to manage those stingy people whom owe you some cash. Just type their names and a debt&apos;s amount and I&apos;ll track that debt for you!.
        /// </summary>
        internal static string Message_About_AppDescription {
            get {
                return ResourceManager.GetString("Message_About_AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use .
        /// </summary>
        internal static string Message_About_SinginInfoLabel_First {
            get {
                return ResourceManager.GetString("Message_About_SinginInfoLabel_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   for signin and backup your data..
        /// </summary>
        internal static string Message_About_SinginInfoLabel_Second {
            get {
                return ResourceManager.GetString("Message_About_SinginInfoLabel_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save this since it&apos;s blank..
        /// </summary>
        internal static string Message_CannotSaveEmptyItems {
            get {
                return ResourceManager.GetString("Message_CannotSaveEmptyItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete this item due to being related to registered debts..
        /// </summary>
        internal static string Message_Error_CannotDeleteDueToRelatedEntities {
            get {
                return ResourceManager.GetString("Message_Error_CannotDeleteDueToRelatedEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This App requires permission to access the network in order to sync and backup your data..
        /// </summary>
        internal static string Message_Error_DeviceWithoutNetworkPermission {
            get {
                return ResourceManager.GetString("Message_Error_DeviceWithoutNetworkPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A failure ocurried while syncing. Please, try again..
        /// </summary>
        internal static string Message_Error_SyncError {
            get {
                return ResourceManager.GetString("Message_Error_SyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation requires you signining again..
        /// </summary>
        internal static string Message_Error_SyncErrorDueToAuthentication {
            get {
                return ResourceManager.GetString("Message_Error_SyncErrorDueToAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurried due to bad Network connection (WiFi or Mobile Data). Please, check your connection status and try again..
        /// </summary>
        internal static string Message_Error_SynErrorDueToBadNetwork {
            get {
                return ResourceManager.GetString("Message_Error_SynErrorDueToBadNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are the people whom owes you or inverse, you took a loan from them. Just requieres their names and an optional description in case you want to save some notes about them..
        /// </summary>
        internal static string Message_Help_ContactsDescription {
            get {
                return ResourceManager.GetString("Message_Help_ContactsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you&apos;ll see the Debts ordered by Contact and clicking them will display the related transactions..
        /// </summary>
        internal static string Message_Help_DashboardDescription {
            get {
                return ResourceManager.GetString("Message_Help_DashboardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They let you mark and organize your debts. You can tag &apos;em indicating whether the debt is from taxies, gal or a social meeting in which you ran out of cash..
        /// </summary>
        internal static string Message_Help_TagsDescription {
            get {
                return ResourceManager.GetString("Message_Help_TagsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation requires signing in. Do you want to register your account and proceed?.
        /// </summary>
        internal static string Message_Profile_SyncRequiresSignin {
            get {
                return ResourceManager.GetString("Message_Profile_SyncRequiresSignin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop! Signing out will erase your profile data and will disable your sync abilities. Do you still want to proceed?.
        /// </summary>
        internal static string Message_Profile_WarningEraseProfileData {
            get {
                return ResourceManager.GetString("Message_Profile_WarningEraseProfileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will delete the selected transaction. Are you sure?.
        /// </summary>
        internal static string Message_Transactions_ActionWillDeleteTransaction {
            get {
                return ResourceManager.GetString("Message_Transactions_ActionWillDeleteTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait, you have no contacts. Before adding a Debt, you must create it first..
        /// </summary>
        internal static string Message_Transactions_ContactsNotFoundAndCreate {
            get {
                return ResourceManager.GetString("Message_Transactions_ContactsNotFoundAndCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a contact to assign this transaction..
        /// </summary>
        internal static string Message_Transactions_MustSelectAContact {
            get {
                return ResourceManager.GetString("Message_Transactions_MustSelectAContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop!.
        /// </summary>
        internal static string Message_Warning_StopTitle {
            get {
                return ResourceManager.GetString("Message_Warning_StopTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait!.
        /// </summary>
        internal static string Message_Warning_WaitTitle {
            get {
                return ResourceManager.GetString("Message_Warning_WaitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dude, {0} pay me the {1} that you already owe me..
        /// </summary>
        internal static string User_Setting_SharingMessageFormat {
            get {
                return ResourceManager.GetString("User_Setting_SharingMessageFormat", resourceCulture);
            }
        }
    }
}
